- name: Install pip
  tags: install_pip
  apt: name=python3-pip state=present

- name: Install python modules for docker
  tags: install_python_modules
  pip:
    name: "{{item.name}}"
    executable: pip3
    version: "{{item.version}}"
    state: present
  with_items:
  - { name: docker, version: 2.0.0 }
  - { name: docker-py, version: 1.10.6 }

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module
- name: Create my hash app Container
  tags: create_hashapp_container
  docker_container:
    name: hashappcontainer
    image: my-hash-app
    state: started
    forcekill: yes
    #restart: yes
    ports:
      - 3000:3000